# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)




# User.create!(name: "Dan", email: "dan@email.com", password_digest: "password", location_id: 1, access: "manager")
# User.create!(name: "Samantha", email: "sam@email.com", password_digest: "password", location_id: 1, access: "standard")
# User.create!(name: "This Guy", email: "guy@email.com", password_digest: "password", location_id: 1, access: "standard")

Location.create!({name: "Municipal Bar", location_type_id: 1, description: "A chic warehouse-style space housing lots of booze, pub food & numerous TVs with late-night hours.", headcount: 0, capacity: 50, cap_percent: 25, address: "216 W Ohio St, Chicago, IL 60654"})
Location.create!({name: "Mercadito", location_type_id: 2, description: "Cocktails and upscale Mexican eats keep this popular hangout bustling with a hip, young crowd.", headcount: 0, capacity: 100, cap_percent: 25, address: "216 W Ohio St, Chicago, IL 60654"})
Location.create!({name: "O'Leary's Public House", location_type_id: 1, description: "Warm Irish pub offering traditional eats & drinks, plus TVs showing Packers games & other sports.", headcount: 0, capacity: 70, cap_percent: 25, address: "541 N Wells St, Chicago, IL 60654"})
Location.create!({name: "Farmhouse Chicago", location_type_id: 2, description: "Funky farm-themed hangout with salvaged decor serving American comfort food, regional beers & wines.", headcount: 0, capacity: 150, cap_percent: 25, address: "228 W Chicago Ave, Chicago, IL 60654"})
Location.create!({name: "Seoul Taco", location_type_id: 2, description: "Funky counter specializing in Korean & Mexican street food plus beer amid murals & boom boxes.", headcount: 0, capacity: 25, cap_percent: 25, address: "738 N Clark St, Chicago, IL 60654"})
Location.create!({name: "Portillo's Hot Dogs", location_type_id: 2, description: "Chicago-born chain for hot dogs, Italian beef sandwiches & more, plus beer & wine, in retro digs.", headcount: 0, capacity: 120, cap_percent: 25, address: "100 W Ontario St, Chicago, IL 60654"})
Location.create!({name: "Fado Irish Pub", location_type_id: 3, description: "A traditional Irish atmosphere, with Guinness, whiskey & pub food faves, plus European soccer on TV.", headcount: 0, capacity: 150, cap_percent: 25, address: "100 W Grand Ave, Chicago, IL 60654"})
Location.create!({name: "Enolo Wine Cafe", location_type_id: 1, description: "Global wines & beers plus pasta, panini & small plates served in a modern space with unique style.", headcount: 0, capacity: 150, cap_percent: 25, address: "450 N Clark St, Chicago, IL 60654"})
Location.create!({name: "The Boss Bar", location_type_id: 1, description: "Long-running hangout featuring pool, TV sports & late hours, plus a menu of burgers & draft beer.", headcount: 0, capacity: 75, cap_percent: 25, address: "420 N Clark St, Chicago, IL 60654"})
Location.create!({name: "Kerryman Irish Bar & Restaurant", location_type_id: 3, description: "Multilevel pub with an after-work scene, offering a menu of Irish dishes & bar food.", headcount: 0, capacity: 25, cap_percent: 25, address: "661 N Clark St, Chicago, IL 60654"})
Location.create!({name: "The Green Door Tavern", location_type_id: 1, description: "Long-running watering hole featuring American fare in a comfy, vintage setting.", headcount: 0, capacity: 110, cap_percent: 25, address: "678 N Orleans St, Chicago, IL 60654"})
Location.create!({name: "Richard's Bar", location_type_id: 1, description: "Tin-ceiling bar with budget beers, hard-boiled eggs & a jukebox filled with rat-pack classics.", headcount: 0, capacity: 100, cap_percent: 25, address: "491 N Milwaukee Ave, Chicago, IL 60654"})
Location.create!({name: "676 Restaurant & Bar", location_type_id: 1, description: "The Omni's 4th-floor eatery serves upscale American fare in a stylish space with rustic accents.", headcount: 0, capacity: 200, cap_percent: 25, address: "676 N Michigan Ave, Chicago, IL 60611"})
Location.create!({name: "Snickers Bar & Grill", location_type_id: 3, description: "Humble bar & grill serving breakfast, lunch & dinner with a huge beer selection & 7 plasma screens.", headcount: 0, capacity: 160, cap_percent: 25, address: "448 N State St, Chicago, IL 60654"})
Location.create!({name: "Theory", location_type_id: 3, description: "This upscale sports bar offers an eclectic menu in a slick, loungey space with plentiful plasma TVs.", headcount: 0, capacity: 80, cap_percent: 25, address: "9 W Hubbard St, Chicago, IL 60654"})
Location.create!({name: "Emerald Loop Bar & Grill", location_type_id: 3, description: "Stained-glass-accented Irish bar with outdoor patio, TVs & bar menu with Irish fare & burgers.", headcount: 0, capacity: 90, cap_percent: 25, address: "216 N Wabash Ave, Chicago, IL 60601"})
Location.create!({name: "Maggiano's Little Italy", location_type_id: 2, description: "Semi-upscale chain for classic Italian fare served family-style in a relaxed, polished space.", headcount: 0, capacity: 140, cap_percent: 25, address: "516 N Clark St, Chicago, IL 60654"})
Location.create!({name: "India House Restaurant ", location_type_id: 2, description: "Offering over 250 menu items, this Indian restaurant has both classic dishes & a lunch buffet.", headcount: 0, capacity: 30, cap_percent: 25, address: "59 W Grand Ave, Chicago, IL 60654"})
Location.create!({name: "LYFE Kitchen", location_type_id: 2, description: "Modern, casual chain serving health-minded, globally inspired food made with local ingredients.", headcount: 0, capacity: 50, cap_percent: 25, address: "413 N Clark St, Chicago, IL 60654"})
Location.create!({name: "Ironside Bar", location_type_id: 1, description: "Sports bar with a steampunk vibe serving craft cocktails & creative bites in nautical digs.", headcount: 0, capacity: 50, cap_percent: 25, address: "546 N Wells St, Chicago, IL 60654"})

Special.create!({name: "Wansas Tequila Shots", price: 5, special_type_id: 1, location_id: 2, day: "Mon", start_time: 0, end_time: 0})
Special.create!({name: "Cerveza", price: 5, special_type_id: 1, location_id: 2, day: "Tue", start_time: 0, end_time: 0})
Special.create!({name: "Cocktails Glasses", price: 5, special_type_id: 1, location_id: 2, day: "Wed", start_time: 0, end_time: 0})
Special.create!({name: "Coocktail Pitchers", price: 5, special_type_id: 1, location_id: 2, day: "Thu", start_time: 0, end_time: 0})
Special.create!({name: "Seasonal Craft Cocktails", price: 5, special_type_id: 1, location_id: 2, day: "Fri", start_time: 0, end_time: 0})
Special.create!({name: "Mimosa Package", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Non-stop-pour Bloody Marys", price: 5, special_type_id: 1, location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Old Fashioned", price: 5, special_type_id: 1, location_id: 2, day: "Mon", start_time: 0, end_time: 0})
Special.create!({name: "Daiquiri", price: 5, special_type_id: 1, location_id: 2, day: "Tue", start_time: 0, end_time: 0})
Special.create!({name: "Jello Shots", price: 5, special_type_id: 1, location_id: 2, day: "Mon", start_time: 0, end_time: 0})
Special.create!({name: "Kamikaze", price: 5, special_type_id: 1, location_id: 2, day: "Fri", start_time: 0, end_time: 0})
Special.create!({name: "Jaegerbombs", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Lemondrops", price: 5, special_type_id: 1, location_id: 2, day: "Thu", start_time: 0, end_time: 0})
Special.create!({name: "Martini", price: 5, special_type_id: 1, location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Manhatan", price: 5, special_type_id: 1, location_id: 2, day: "Fri", start_time: 0, end_time: 0})
Special.create!({name: "Mojito", price: 5, special_type_id: 1, location_id: 2, day: "Fri", start_time: 0, end_time: 0})
Special.create!({name: "Brandy Sour", price: 5, special_type_id: 1, location_id: 2, day: "Wed", start_time: 0, end_time: 0})
Special.create!({name: "Gibson", price: 5, special_type_id: 1, location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Acapulco Cocktail", price: 5, special_type_id: 1, location_id: 2, day: "Wed", start_time: 0, end_time: 0})
Special.create!({name: "Amber Moon", price: 5, special_type_id: 1, location_id: 2, day: "Thu", start_time: 0, end_time: 0})
Special.create!({name: "Non-stop-pour Bloody Marys", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Old Fashioned", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Daiquiri", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Daiquiri", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Jello Shots", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Wansas Tequila Shots", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Cerveza", price: 5, special_type_id: 1, location_id: 2, day: "Wed", start_time: 0, end_time: 0})
Special.create!({name: "Jaegerbombs", price: 5, special_type_id: 1, location_id: 2, day: "Thu", start_time: 0, end_time: 0})
Special.create!({name: "Daiquiri", price: 5, special_type_id: 1, location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Jello Shots", price: 5, special_type_id: 1, location_id: 2, day: "Fri", start_time: 0, end_time: 0})
Special.create!({name: "Manhatan", price: 5, special_type_id: 1, location_id: 2, day: "Tue", start_time: 0, end_time: 0})
Special.create!({name: "Mojito", price: 5, special_type_id: 1, location_id: 2, day: "Fri", start_time: 0, end_time: 0})
Special.create!({name: "Brandy Sour", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Gibson", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Cerveza", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Cocktails Glasses", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Manhatan", price: 5, special_type_id: 1, location_id: 2, day: "Sat", start_time: 0, end_time: 0})
Special.create!({name: "Mojito", price: 5, special_type_id: 1, location_id: 2, day: "Thu", start_time: 0, end_time: 0})
Special.create!({name: "Brandy Sour", price: 5, special_type_id: 1, location_id: 2, day: "Wed", start_time: 0, end_time: 0})
Special.create!({name: "Gibson", price: 5, special_type_id: 1, location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Hamburger", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Sliders", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Cheese Fries", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Cheese Sticks", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Hot Dogs", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Chicken Wings", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Cheese Curds", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Cheese Burger", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Cheese Pizza", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Sausage Pizza", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Macaroni", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Popcorn", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Mushroom Pizza", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Grilled Cheese", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Fries", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Nachos", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Chicken Fingers", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Onion Rings", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Curly Fries", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Japaleno Poppers", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Buffalo Wings", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Quesadilla", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Soft Pretzel", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Chips and Salsa", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Waffle Fries", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Pulled Pork", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "BLT", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Tator Tots", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Chili Dog", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Toasted Ravioli", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Panini", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Egg Rolls", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Hummus", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Chicken Alfredo", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Meatloaf", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Scotch Egss", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Chili Cheese Fries", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Steak", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Sushi Rolls", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})
Special.create!({name: "Chicken Sandwich", price: 5, special_type_id: 2 , location_id: 2, day: "Sun", start_time: 0, end_time: 0})

SpecialType.create!(name: "Drink")
SpecialType.create!(name: "Food")


LocationType.create!(name: "Bar")
LocationType.create!(name: "Restaurant")
LocationType.create!(name: "Bar/Restaurant")